### ISSUE TITLE
args separator after split_argfile

### ISSUE THREAD

**Issue by artiomn** [waf-project/waf#1843] opened 2016-10-25 14:02 UTC
```python
		if not isinstance(cmd, str) and (len(repr(cmd)) >= 8192 if Utils.is_win32 else len(cmd) > 200000):
			cmd, args = self.split_argfile(cmd)
			try:
				(fd, tmp) = tempfile.mkstemp()
->				os.write(fd, '\r\n'.join(args).encode())
```

I have error from cctools with this separator .
Space is a more natural separator for arguments.
Could you replace '\r\n' with a space?

Error:
```
Assertion failed!

Program: C:\cygwin\opt\crosstool64\x86_64-apple-darwin\clang-703.0.31-cctools-88
6\bin\x86_64-apple-darwin-clang++.exe
File: H:/MinGW/msys/1.0/home/sv/crossbuild/mac/build/clang-703.0.31/src/lib/Opti
on/OptTable.cpp, Line 278

Expression: Index >= End && "Unexpected parser error."

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
0x00000000023C4D67 (0x0000000000000001 0x000000001E0C1AD5 0x00007FFC4A46CA70 0x0
00000000000000A)
0x00007FFC4A46633B (0x0000000000000001 0x00007FFC1E0C1AD5 0x0000000003658FC0 0x0
000000003658F60), raise() + 0x1FB bytes(s)
0x00007FFC4A4699FE (0x00007FFC4A493D30 0x0000000003267000 0x00000000034F2FD0 0x0
000000000000200), abort() + 0x2E bytes(s)
0x00000000024181F2 (0x00000000000001A6 0x0000000003658F60 0x0000000000000014 0x0
0000000000001A6)
0x00000000024182A7 (0x00000000034F2EA0 0x000000000023F090 0x000000000023E94C 0x0
000000000000000)
0x00000000015AFD67 (0x000000000023EA80 0x000000000238DDF0 0x000000000023EC40 0x0
00000000023ECE0)
0x00000000028538C1 (0x0000000000000001 0x0000000000000033 0x0000000000000000 0x0
000000000000000)
0x00000000004013F8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0
000000000000000)
0x000000000040151B (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0
000000000000000)
0x00007FFC4C2513D2 (0x00007FFC4C2513B0 0x0000000000000000 0x0000000000000000 0x0
000000000000000), BaseThreadInitThunk() + 0x22 bytes(s)
0x00007FFC4C3A54E4 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0
000000000000000), RtlUserThreadStart() + 0x34 bytes(s)

d:\repos\third-party\icu\build>botepad c:\users\artem~1.nec\appdata\local\temp\t
mpz7d7s6
'botepad' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by ita1024** [comment] 2016-10-26 20:39
I believe that such newlines are required by certain applications. We need to verify that no regression would happen because of this, and I am also reluctant to make a change as the spaces would also make those argument files less readable.

The default cctools does not support @argfile so you are essentially asking us to tune Waf for your particular cctools fork. Aside from submitting a proper patch to cctools, I think that you should try to use make your own Waf extension and use the technique mentioned in another ticket to support the desired functionality (override Task methods in subclasses, in this case it is `exec_command`).

**Comment by artiomn** [comment] 2016-10-27 08:24
> I believe that such newlines are required by certain applications.

Which, for example?
Spaces are command line arguments separator, I think it's more natural (especially, if some tools use '@' as a `read file`->`substitute file content` without processing file).

> also make those argument files less readable

But you always delete this temporary arguments files.

> Aside from submitting a proper patch to cctools

I'll create proper patch and try to submit it, but I think, it will be a long process...

> and use the technique mentioned in another ticket to support the desired functionality 

I've done it already, but I don't want to have a patched `waflib`.

**Comment by ita1024** [comment] 2016-10-27 12:54
1. That is an opinion. Are you certain that spaces will not break any existing application?
2. This does not mean that such files are never read or that they will never be read
3. Yes, that can take time.
4. I have to concur: I do not want the Waf source code to be optimized for strange non-official hacks!

**Comment by artiomn** [comment] 2016-10-27 16:44
> That is an opinion. Are you certain that spaces will not break any existing application?

Of course, not. Equally, you can't be certain, that \n\l don't break any existing application. :-/
But, I think, that is a normal behaviour - to understand spaces as a parameters separators. Very badly-behaviour applications maybe will be broken.
But not msvc or gcc.

> I have to concur: I do not want the Waf source code to be optimized for strange non-official hacks!

It doesn't look like a hack.

**Comment by artiomn** [comment] 2016-10-27 16:50
And not only me have caught this problem (in another ways):
https://code.google.com/p/android/issues/detail?id=195801
https://groups.google.com/forum/#!topic/crystax-ndk/7EXm4pds0VU

> The issue is that clang is crashing if arguments in options.txt are placed on two separate lines.
> For example this in options.txt will cause a crash:
> -x
> c
> -target
> armv7-none-linux-android
>
> While this will not:
> -x c
> -target armv7-none-linux-android

**Comment by artiomn** [comment] 2016-10-27 16:54
But, in principle, I can fix it in clang...

**Comment by artiomn** [comment] 2016-10-28 12:28
However, as a notice:
> Options in file are separated by whitespace. A whitespace character may be included in an option by surrounding the entire option in either single or double quotes.

https://linux.die.net/man/1/ar

**Comment by artiomn** [comment] 2016-10-28 12:46
Now it's working, like a GNU linker.

**Comment by ita1024** [comment] 2016-10-28 17:09
Perfect, so we can close this then.

**Closed** 2016-10-28 17:09 UTC
