### ISSUE TITLE
Preserve colored output from compiler

### ISSUE THREAD

**Issue by jhasse** [waf-project/waf#1555] opened 2015-04-15 03:40 UTC
When using clang with colored output running through waf is uncolored.

This is how I fix it in SCons:
```
env['ENV']['TERM'] = os.environ['TERM']
```

**Comment by kirbyfan64** [comment] 2015-04-15 14:47
That's kind of ucky. The best way to do it?

Add a command-line option to your build script labeled `--use-color`. If enabled, pass `-fdiagnostics-color` to the compiler.

**Comment by ita1024** [comment] 2015-04-18 18:52
There is no problem with colorgcc. Are you certain that the problem is in Waf?

**Comment by jhasse** [comment] 2015-04-19 01:45
I guess colorgcc always uses colors just like `-fdiagnostics-color`. What I'm talking about is the automatic detection of the compiler if the terminal supports color which wafs seems to suppress somehow (I guess it's because of the TERM env var).

Example:
![bildschirmfoto vom 2015-04-19 03 41 15](https://cloud.githubusercontent.com/assets/80071/7217800/09135738-e646-11e4-9a6f-62e854443cc4.png)

**Comment by kirbyfan64** [comment] 2015-04-19 02:03
It's not Waf's fault; Clang and maybe colorgcc don't output colors if they aren't printing to a real terminal.

**Comment by ita1024** [comment] 2015-04-19 09:13
Waf does not suppress environment variables; try for example:
        bld.env.FOO = 'env'
        bld(rule="shell=1 bash -c ${FOO}", always=True, shell=True)
        bld(rule="bash -c ${FOO}", always=True, shell=False)

Is there any other explanation?

**Comment by jhasse** [comment] 2015-04-19 12:52
When I run

```python
    bld(rule="env | grep TERM", always=True, shell=True)
```

It gives me

```
COLORTERM=gnome-terminal
TERM=vt100
```

But running it myself gives me
```
TERM=xterm
COLORTERM=gnome-terminal
```

**Comment by ita1024** [comment] 2015-04-19 14:50
does clang refuse to output colors if the term is vt100?

**Comment by kirbyfan64** [comment] 2015-04-19 14:56
@ita1024 Clang refuses to output colors if the terminal doesn't look like a TTY (I *believe* it just calls `istty`); not sure about the effect of the `TERM` environment variable.

**Comment by lu-zero** [comment] 2015-04-26 10:25
clang uses right now `terminfo`/`libcurses` that I know so you should look there for a definitive answer.

**Comment by ita1024** [comment] 2015-04-26 15:35
Setting anything in TERM will not work. We have no possible fix.

**Comment by jhasse** [comment] 2015-04-27 11:25
Please reopen. It works with scons so there must be something that can be done.

**Comment by kirbyfan64** [comment] 2015-04-27 15:22
@jhasse Look, it's because (I believe) Waf buffers the command output. There's *nothing* that really can easily be done. It's just a sad issue. Just pass `-fdiagnostics-color`.

**Comment by jhasse** [comment] 2015-04-27 15:53
I see. I will look into waf's source and work on a patch.

Passing -fdiagnostics-color is a hack in my opinion, I'm looking for a fix
which will enable colors out of the box (not only with my wscript).

**Comment by kirbyfan64** [comment] 2015-04-27 16:46
It's not a hack. It's there for a reason. You can't really patch that without getting issues when running multi-threaded builds; just try `make -j` with multiple source files that have errors.

**Comment by jhasse** [comment] 2015-04-27 16:48
I don't want to remove the buffering, but a way to tell clang that it
should output as if it was called directly on the console.

**Comment by kirbyfan64** [comment] 2015-04-27 18:38
@jhasse Well, some also explicitly do not want this. When you're using log files, there's a 99% change that you do NOT want ANSI color codes in your file...

**Comment by ita1024** [comment] 2015-04-27 21:23
Nothing about this

**Comment by jhasse** [comment] 2015-04-27 22:39
@kirbyfan64 And that's exactly the reason why `-fdiagnostics-color` is not a perfect solution as it will result in clang always outputting ANSI color codes.

@ita1024 Thanks for reopening :) I will work something out, but I might also have to look into clang's source.

**Comment by che2** [comment] 2015-05-20 17:14
Ninja encountered a similar issue: https://github.com/martine/ninja/issues/174
Their fix is to add a special flag, CLANG_FORCE_COLOR_DIAGNOSTICS, to set the -fdiagnostics-color flag manually.  And the in their text output function, strip out the ANSI color codes if it's not writing to a terminal: https://github.com/martine/ninja/commit/2ef3a546476987d6565141337c6309e7ae60f9fd

Perhaps we could use the same idea.

**Comment by lu-zero** [comment] 2015-05-20 17:47
A solution might be to use `pty.spawn` to execute if output-as-console is requested.

**Comment by ita1024** [comment] 2015-05-20 19:43
che2: from the comments above, jhass does nt want -fdiagnostics-color.

lu-zero: "Because pseudo-terminal handling is highly platform dependent, there is code to do it only for Linux".

No outcomes for a month, closing this thread now.

**Closed by ita1024** 2015-05-20 19:43 UTC

**Comment by jhasse** [comment] 2015-05-21 08:36
@che2 I didn't know about CLANG_FORCE_COLOR_DIAGNOSTICS, thanks :) Why isn't ninja just setting this flag when running through a terminal instead of stripping the ANSI color codes when not?

What I don't like about CLANG_FORCE_COLOR_DIAGNOSTICS is that it's specific to clang. IMHO the best solution would be an environment which all programs recognize. I've created a page to get the ball rolling: http://bixense.com/clicolors/
I will open a bug report for clang soon :) In theory all waf/ninja/etc. need to do then is to set CLICOLOR_FORCE.

**Comment by jhasse** [comment] 2016-05-09 12:42
I've created a bug report for clang here: https://llvm.org/bugs/show_bug.cgi?id=23609

So far only CMake accepted my patch and uses `CLICOLOR_FORCE` to enable its own colored output. Would you accept a similar PR for waf?
