### ISSUE TITLE
Treat Fortran modules properly in resumed compilations

### ISSUE THREAD

**Issue by haraldkl** [waf-project/waf#1580] opened 2015-05-28 17:49 UTC
I am facing the problem, described in this pull request: https://github.com/waf-project/waf/pull/1578. I think, I understand the issue now better.
The problem is, that for Fortran tasks,  there are two phases. One before all Fortran tasks are ready and the module dependencies can be computed and one after the module dependencies have been computed. In the first phase we check the super runnable status of all Fortran tasks to see wether all of them are ready and we can proceed to computing the module dependencies.
Now, in this phase the run_after list of the Fortran tasks is still empty, so Task.runnable_status will attempt to compute the signature of the task. And as we have a scan function defined for the Fortran tasks, it will also try to run sig_implicit_deps (and only catch TaskRescan errors).
For resumed compilations, there are (implicit) task_sigs available from the previous run, and we try to get the signature of the nodes this task is depending on (also cached). This might fail now, because the modules potentially do not exist yet and thus, do not have a signature.

How is this fixed best? Should the (implicit) task_sigs or node_deps, or both be reset in the first phase for Fortran tasks before calling the runnable_status? Or should the attributeError be fetched and treated accordingly? Or should the are_implicit_nodes_ready routine be reimplemented by the fc class?

I still do not fully understand what is going on. Mainly, why it actually works so often. I need to have two subsequent failed compilations to get the missing signature error, and the project needs to be fairly large, it seems.
The caching logic appears to me to be broken for Fortran modules, because the fc scanner returns an empty list of nodes. Thus, after computing the module dependencies, the node_deps list is filled with all the node dependencies, but afterwards they get pruned by rescans for the implicit dependencies. When the state is then written into the cache, there are all those task_sigs defined with empty node_deps. If this is not wrong, it is at least very confusing.

Maybe it would be better to get rid of this two phase separation, and instead rely on the rescanning when a node is missing? But I am a little bit afraid of that, because the fc.runnable_status docstring says something about concurrency issues, that are avoided by the current approach?

**Comment by ita1024** [comment] 2015-05-28 21:19
Are the same fortran file used by several targets/task generators?

**Comment by haraldkl** [comment] 2015-05-28 21:34
Not directly, but the resulting objects are used by multiple targets.

**Comment by ita1024** [comment] 2015-05-28 22:16
Are you absolutely positive that the issue can be reproduced with -j1 on *all* executions?

The .mod files do always get a .sig attribute (node.sig = Utils.SIG_NIL).

**Comment by haraldkl** [comment] 2015-05-28 22:31
Yes, it looks like this:
(first initial run in clean directory, then a repetition of the failed compilation, and a second try, wherein it then fails).

[275/322] Processing treelm/source/tem_general_module.f90
[276/322] Processing source/sdr_harvesting/sdr_hvs_config_module.f90
/Users/klimach/scratch/seeder_test/source/sdr_harvesting/sdr_hvs_config_module.f90:75:40:

     call hvs_output_load( me   = failme%output, &
                                        1
Error: Symbol 'failme' at (1) has no IMPLICIT type

Waf: Leaving directory `/Users/klimach/scratch/seeder_test/build/debug'
Build failed
 -> task in 'sdr_hvs_objs' failed (exit status 1): 
	{task 4348476048: fc sdr_hvs_config_module.f90 -> sdr_hvs_config_module.f90.4.o,sdr_hvs_config_module.mod}
['mpif90', '-fbacktrace', '-fbounds-check', '-g', '-Wall', '-Wconversion', '-Wimplicit-interface', '-Wunderflow', '-W', '-frange-check', '-Dhas_c_sizeof=1', '-c', '-o', '/Users/klimach/scratch/seeder_test/build/debug/source/sdr_harvesting/sdr_hvs_config_module.f90.4.o', '/Users/klimach/scratch/seeder_test/source/sdr_harvesting/sdr_hvs_config_module.f90']
Haralds-MacBook-Pro:seeder_test klimach$ ./waf debug -j1
Waf: Entering directory `/Users/klimach/scratch/seeder_test/build/debug'
Compiler: GFORTRAN
Version : 5.1.0
Flags   : -fbacktrace -fbounds-check -g -Wall -Wconversion -Wimplicit-interface -Wunderflow -W -frange-check
Using the *dummy* FFTW here!
[276/322] Processing source/sdr_harvesting/sdr_hvs_config_module.f90
/Users/klimach/scratch/seeder_test/source/sdr_harvesting/sdr_hvs_config_module.f90:75:40:

     call hvs_output_load( me   = failme%output, &
                                        1
Error: Symbol 'failme' at (1) has no IMPLICIT type

Waf: Leaving directory `/Users/klimach/scratch/seeder_test/build/debug'
Build failed
 -> task in 'sdr_hvs_objs' failed (exit status 1): 
	{task 4508692112: fc sdr_hvs_config_module.f90 -> sdr_hvs_config_module.f90.4.o,sdr_hvs_config_module.mod}
['mpif90', '-fbacktrace', '-fbounds-check', '-g', '-Wall', '-Wconversion', '-Wimplicit-interface', '-Wunderflow', '-W', '-frange-check', '-Dhas_c_sizeof=1', '-c', '-o', '/Users/klimach/scratch/seeder_test/build/debug/source/sdr_harvesting/sdr_hvs_config_module.f90.4.o', '/Users/klimach/scratch/seeder_test/source/sdr_harvesting/sdr_hvs_config_module.f90']
Haralds-MacBook-Pro:seeder_test klimach$ ./waf debug -j1
Waf: Entering directory `/Users/klimach/scratch/seeder_test/build/debug'
Compiler: GFORTRAN
Version : 5.1.0
Flags   : -fbacktrace -fbounds-check -g -Wall -Wconversion -Wimplicit-interface -Wunderflow -W -frange-check
Using the *dummy* FFTW here!
Waf: Leaving directory `/Users/klimach/scratch/seeder_test/build/debug'
Build failed
Traceback (most recent call last):
  File "/Users/klimach/scratch/seeder_test/.waf-1.8.7-315a7b482a73bed5780df933adccfde1/waflib/Runner.py", line 150, in task_status
    return tsk.runnable_status()
  File "/Users/klimach/scratch/seeder_test/.waf-1.8.7-315a7b482a73bed5780df933adccfde1/waflib/Tools/fc.py", line 46, in runnable_status
    ret=tsk.runnable_status()
  File "/Users/klimach/scratch/seeder_test/.waf-1.8.7-315a7b482a73bed5780df933adccfde1/waflib/Tools/fc.py", line 40, in runnable_status
    return super(fc,self).runnable_status()
  File "/Users/klimach/scratch/seeder_test/.waf-1.8.7-315a7b482a73bed5780df933adccfde1/waflib/Task.py", line 313, in runnable_status
    new_sig=self.signature()
  File "/Users/klimach/scratch/seeder_test/.waf-1.8.7-315a7b482a73bed5780df933adccfde1/waflib/Task.py", line 302, in signature
    self.sig_implicit_deps()
  File "/Users/klimach/scratch/seeder_test/.waf-1.8.7-315a7b482a73bed5780df933adccfde1/waflib/Task.py", line 386, in sig_implicit_deps
    if prev==self.compute_sig_implicit_deps():
  File "/Users/klimach/scratch/seeder_test/.waf-1.8.7-315a7b482a73bed5780df933adccfde1/waflib/Task.py", line 424, in compute_sig_implicit_deps
    upd(k.get_bld_sig())
  File "/Users/klimach/scratch/seeder_test/.waf-1.8.7-315a7b482a73bed5780df933adccfde1/waflib/Node.py", line 459, in get_bld_sig
    self.cache_sig=ret=self.sig
AttributeError: sig

I also reproduced this on other machines.

**Comment by haraldkl** [comment] 2015-05-28 22:43
> The .mod files do always get a .sig attribute (node.sig = Utils.SIG_NIL).

Yes, but the signature is called for a node from the node_deps, which was carried over from the last waf run, and the task which is to create the module was not run yet (it happens in the first phase, where we are still trying to figure out, what outputs will be produced). So, the node_deps has stored module nodes from the last computation of all produced modules, but in the current run, that node was not touched yet and does not have a sig.

**Comment by ita1024** [comment] 2015-05-28 22:54
It should not matter as the fortran .mod node objects are all created in one place, and as a signature is bound to it immediately. 

Or are you talking about a missing signature on a node object that is not a .mod file?

**Comment by haraldkl** [comment] 2015-05-28 22:59
The AttributeError arises for a node object of a .mod file.

**Comment by haraldkl** [comment] 2015-05-28 23:08
with some prints:

        def compute_sig_implicit_deps(self):
                upd=self.m.update
                bld=self.generator.bld
                self.are_implicit_nodes_ready()
                print('compute_sig_implicit_deps({0}):'.format(self))
                for k in bld.node_deps.get(self.uid(),[]):
                        print('   node_dep: {0}'.format(k))
                        upd(k.get_bld_sig())
                return self.m.digest()


compute_sig_implicit_deps(treelm/utests/tem_parallel_singlelevel_test.f90):
   node_dep: tem_utestenv_module.mod
Waf: Leaving directory `/Users/klimach/scratch/seeder_test/build/debug'
Build failed
Traceback (most recent call last):
  File "/Users/klimach/scratch/seeder_test/.waf-1.8.7-315a7b482a73bed5780df933adccfde1/waflib/Runner.py", line 150, in task_status
    return tsk.runnable_status()
  File "/Users/klimach/scratch/seeder_test/.waf-1.8.7-315a7b482a73bed5780df933adccfde1/waflib/Tools/fc.py", line 46, in runnable_status
    ret=tsk.runnable_status()
  File "/Users/klimach/scratch/seeder_test/.waf-1.8.7-315a7b482a73bed5780df933adccfde1/waflib/Tools/fc.py", line 40, in runnable_status
    return super(fc,self).runnable_status()
  File "/Users/klimach/scratch/seeder_test/.waf-1.8.7-315a7b482a73bed5780df933adccfde1/waflib/Task.py", line 313, in runnable_status
    new_sig=self.signature()
  File "/Users/klimach/scratch/seeder_test/.waf-1.8.7-315a7b482a73bed5780df933adccfde1/waflib/Task.py", line 302, in signature
    self.sig_implicit_deps()
  File "/Users/klimach/scratch/seeder_test/.waf-1.8.7-315a7b482a73bed5780df933adccfde1/waflib/Task.py", line 386, in sig_implicit_deps
    if prev==self.compute_sig_implicit_deps():
  File "/Users/klimach/scratch/seeder_test/.waf-1.8.7-315a7b482a73bed5780df933adccfde1/waflib/Task.py", line 426, in compute_sig_implicit_deps
    upd(k.get_bld_sig())
  File "/Users/klimach/scratch/seeder_test/.waf-1.8.7-315a7b482a73bed5780df933adccfde1/waflib/Node.py", line 459, in get_bld_sig
    self.cache_sig=ret=self.sig
AttributeError: sig

**Comment by ita1024** [comment] 2015-05-28 23:15
Run with waf 1.8.10 please. Do you see how a created .mod node object could end up without a .sig attribute?

**Comment by haraldkl** [comment] 2015-05-28 23:18
I tried a rough sketch of a fc class without the two phases. It would need some more work, but it works without the issue above. I removed the redefinition of the runnable_status method and change the scan method like this:

        def scan(self):
                """scanner for fortran dependencies"""
                bld=self.generator.bld
                key=self.uid()

                # If we parsed the source file already, use the old result,
                # otherwise parse it now.
                if key in bld.raw_deps:
                        rawnames = bld.raw_deps[key]
                        usenodes = bld.node_deps[key]
                else:
                        tmp=fc_scan.fortran_parser(self.generator.includes_nodes)
                        tmp.task=self
                        tmp.start(self.inputs[0])
                        rawnames = tmp.names
                        usenodes = tmp.nodes
                        if Logs.verbose:
                                Logs.debug('deps: FC deps for %r: %r; unresolved %r'%(self.inputs,tmp.nodes,tmp.names))

                usenames = []
                modnames = []

                # Create the lookup table for implicit nodes
                try:
                        cache = bld.dct_implicit_nodes
                except AttributeError:
                        bld.dct_implicit_nodes = cache = {}

                try:
                        dct = cache[bld.cur]
                except KeyError:
                        dct = cache[bld.cur] = {}
                        for tsk in bld.cur_tasks:
                                for x in tsk.outputs:
                                        dct[x] = tsk

                # First check all modules that will be produced by this
                # task and add them to the outputs if they are not in there
                # already.
                for x in rawnames:
                        if x.startswith('MOD@'):
                                name=bld.modfile(x.replace('MOD@',''))
                                if name not in modnames:
                                        modnames.append(name)
                                node=bld.srcnode.find_or_declare(name)
                                if not hasattr(node,'sig'):
                                        node.sig=Utils.SIG_NIL
                                if node not in self.outputs:
                                        self.set_outputs(node)
                                dct[node] = self

                # Now check the modules we are depending on.
                # Ignore modules which are used in the same file as they are
                # defined.
                # If any of the module files is not yet existing, raise a
                # TaskNotReady error.
                for x in rawnames:
                        if x.startswith('USE@'):
                                # Ugly hack to ignore intrinsic modules
                                if x.lower() not in ['use@iso_c_binding', 'use@mpi', 'use@iso_fortran_env', 'use@ieee_exceptions', 'use@ieee_arithmetic', 'use@ieee_features']:
                                        name=bld.modfile(x.replace('USE@',''))
                                        if name not in modnames:
                                                node=bld.srcnode.find_resource(name)
                                                if not node:
                                                        raise Errors.TaskNotReady('not ready')
                                                if name not in usenames:
                                                        usenames.append(name)
                                                if node not in self.outputs:
                                                        if node not in usenodes:
                                                                usenodes.append(node)
                return(usenodes,rawnames)

And I redefine are_implicit_nodes_ready to post TaskNotReady if files from the dependency list are missing:

        def are_implicit_nodes_ready(self):
                """ Check if implicit nodes are ready for Fortran tasks,
                    takes care of not existing module files. """
                bld=self.generator.bld
                try:
                        cache=bld.dct_implicit_nodes
                except AttributeError:
                        bld.dct_implicit_nodes=cache={}
                try:
                        dct=cache[bld.cur]
                except KeyError:
                        dct=cache[bld.cur]={}
                        for tsk in bld.cur_tasks:
                                for x in tsk.outputs:
                                        dct[x]=tsk

                modified=False
                for x in bld.node_deps.get(self.uid(),[]):
                        if x in dct:
                                self.run_after.add(dct[x])
                                modified=True
                        else:
                                if not os.path.isfile(x.abspath()):
                                        raise Errors.TaskNotReady('not ready')
                if modified:
                        for tsk in self.run_after:
                                if not tsk.hasrun:
                                        raise Errors.TaskNotReady('not ready')

I don't know wether such an approach would be a good idea, it still looks somewhat complicated.

**Comment by haraldkl** [comment] 2015-05-28 23:24
> Run with waf 1.8.10 please.
Of course, sorry.

> Do you see how a created .mod node object could end up without a .sig attribute?
I don't fully understand what is going on. As I tried to explain above, after the modules have all been defined at one point in time, the node_deps are filled, but they then get killed again by the fc scanner, and in the end when they are stored, they are completely different. So it might be that the signature also gets killed?

**Comment by haraldkl** [comment] 2015-05-28 23:39
The problem persists with the latest clone.

    Haralds-MacBook-Pro:seeder_test klimach$ ./waf debug -j1
    Waf: Entering directory `/Users/klimach/scratch/seeder_test/build/debug'
    Compiler: GFORTRAN
    Version : 5.1.0
    Flags   : -fbacktrace -fbounds-check -g -Wall -Wconversion -Wimplicit-interface -Wunderflow -W -frange-check
    Using the *dummy* FFTW here!
    [276/322] Processing source/sdr_harvesting/sdr_hvs_config_module.f90
    /Users/klimach/scratch/seeder_test/source/sdr_harvesting/sdr_hvs_config_module.f90:75:40:

         call hvs_output_load( me   = failme%output, &
                                            1
    Error: Symbol 'failme' at (1) has no IMPLICIT type

    Waf: Leaving directory `/Users/klimach/scratch/seeder_test/build/debug'
    Build failed
     -> task in 'sdr_hvs_objs' failed (exit status 1):
        {task 4469141200: fc sdr_hvs_config_module.f90 -> sdr_hvs_config_module.f90.4.o,sdr_hvs_config_module.mod}
    ['mpif90', '-fbacktrace', '-fbounds-check', '-g', '-Wall', '-Wconversion', '-Wimplicit-interface', '-Wunderflow', '-W', '-frange-check', '-Dhas_c_sizeof=1', '-c', '-o', '/Users/klimach/scratch/seeder_test/build/debug/source/sdr_harvesting/sdr_hvs_config_module.f90.4.o', '/Users/klimach/scratch/seeder_test/source/sdr_harvesting/sdr_hvs_config_module.f90']
    Haralds-MacBook-Pro:seeder_test klimach$ ./waf debug -j1
    Waf: Entering directory `/Users/klimach/scratch/seeder_test/build/debug'
    Compiler: GFORTRAN
    Version : 5.1.0
    Flags   : -fbacktrace -fbounds-check -g -Wall -Wconversion -Wimplicit-interface -Wunderflow -W -frange-check
    Using the *dummy* FFTW here!
    Waf: Leaving directory `/Users/klimach/scratch/seeder_test/build/debug'
    Build failed
    Traceback (most recent call last):
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Runner.py", line 150, in task_status
        return tsk.runnable_status()
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Tools/fc.py", line 45, in runnable_status
        ret=tsk.runnable_status()
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Tools/fc.py", line 39, in runnable_status
        return super(fc,self).runnable_status()
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Task.py", line 313, in runnable_status
        new_sig=self.signature()
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Task.py", line 302, in signature
        self.sig_implicit_deps()
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Task.py", line 386, in sig_implicit_deps
        if prev==self.compute_sig_implicit_deps():
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Task.py", line 424, in compute_sig_implicit_deps
        upd(k.get_bld_sig())
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Node.py", line 459, in get_bld_sig
        self.cache_sig=ret=self.sig
    AttributeError: sig

**Comment by haraldkl** [comment] 2015-05-29 00:23
I checked the sigs now right before storing and after loading.
In Build.restore:

                                        for x in SAVED_ATTRS:
                                                setattr(self,x,data[x])
                                        missingsig = False
                                        for nd in self.node_deps:
                                                for node in self.node_deps[nd]:
                                                        if not hasattr(node, 'sig'):
                                                                missingsig = True
                                                                print('node {0} has no sig!'.format(node))
                                        if not missingsig: print('No missing sig after restoring data')

and in Build.store:

        def store(self):
                data={}
                for x in SAVED_ATTRS:
                        data[x]=getattr(self,x)
                missingsig = False
                for nd in data['node_deps']:
                        for node in data['node_deps'][nd]:
                                if not hasattr(node, 'sig'):
                                        missingsig = True
                                        print('node {0} has no sig!'.format(node))

This results in the following output:

    [278/322] Processing source/sdr_harvesting/sdr_hvs_config_module.f90
    /Users/klimach/scratch/seeder_test/source/sdr_harvesting/sdr_hvs_config_module.f90:75:40:

         call hvs_output_load( me   = failme%output, &
                                            1
    Error: Symbol 'failme' at (1) has no IMPLICIT type

    No missing sig in storing data
    Waf: Leaving directory `/Users/klimach/scratch/seeder_test/build/debug'
    Build failed
     -> task in 'sdr_hvs_objs' failed (exit status 1):
        {task 4346495120: fc sdr_hvs_config_module.f90 -> sdr_hvs_config_module.f90.4.o,sdr_hvs_config_module.mod}
    ['mpif90', '-fbacktrace', '-fbounds-check', '-g', '-Wall', '-Wconversion', '-Wimplicit-interface', '-Wunderflow', '-W', '-frange-check', '-Dhas_c_sizeof=1', '-c', '-o', '/Users/klimach/scratch/seeder_test/build/debug/source/sdr_harvesting/sdr_hvs_config_module.f90.4.o', '/Users/klimach/scratch/seeder_test/source/sdr_harvesting/sdr_hvs_config_module.f90']
    Haralds-MacBook-Pro:seeder_test klimach$ ./waf debug -j1
    node sdr_boundary_module.mod has no sig!
    node sdr_hvs_config_module.mod has no sig!
    node sdr_boundary_module.mod has no sig!
    node sdr_flooding_module.mod has no sig!
    node sdr_proto2treelm_module.mod has no sig!
    Waf: Entering directory `/Users/klimach/scratch/seeder_test/build/debug'
    Compiler: GFORTRAN
    Version : 5.1.0
    Flags   : -fbacktrace -fbounds-check -g -Wall -Wconversion -Wimplicit-interface -Wunderflow -W -frange-check
    Using the *dummy* FFTW here!
    Waf: Leaving directory `/Users/klimach/scratch/seeder_test/build/debug'
    Build failed
    Traceback (most recent call last):
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Runner.py", line 150, in task_status
        return tsk.runnable_status()
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Tools/fc.py", line 45, in runnable_status
        ret=tsk.runnable_status()
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Tools/fc.py", line 39, in runnable_status
        return super(fc,self).runnable_status()
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Task.py", line 313, in runnable_status
        new_sig=self.signature()
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Task.py", line 302, in signature
        self.sig_implicit_deps()
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Task.py", line 386, in sig_implicit_deps
        if prev==self.compute_sig_implicit_deps():
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Task.py", line 424, in compute_sig_implicit_deps
        upd(k.get_bld_sig())
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Node.py", line 459, in get_bld_sig
        self.cache_sig=ret=self.sig
    AttributeError: sig

So it appears like the sig attributes should be all there when storing the node_deps, but after loading them, some are mysteriously gone. Can this be? Am I doing something wrong?

**Comment by haraldkl** [comment] 2015-05-29 00:30
If I set the missing node.sig to Utils.SIG_NIL in Build.restore, the problem is also fixed. Still, I have no idea, how this unpickling goes wrong.

**Comment by ita1024** [comment] 2015-05-29 06:28
Are you using any extensions? And which python version are you using? If you really want to look at the data structure, iterate from bld.root besides considering bld.node_deps.

Rewriting the whole thing does not solve the problem either, and probably introduces new issues. Let us focus on the current problem instead.

**Comment by haraldkl** [comment] 2015-05-29 06:43
It's python 2.7.6. With extensions you mean extensions to waf or to Python? I am using a preprocessing class in waf to process .fpp files into .f90 files, but the problem arises for files which are not preprocessed. I also include doxygen, eclipse and print_commands from extras.

Can it be related to cache_sig? That attribute gets deleted in various places and printing it when storing reveals in the first run:

     node sdr_prototree_module.mod has no cache_sig!
     node tem_utestenv_module.mod has no cache_sig!
     node tem_utestenv_module.mod has no cache_sig!
     node tem_utestenv_module.mod has no cache_sig!
     node sdr_prototree_module.mod has no cache_sig!
     node sdr_config_module.mod has no cache_sig!
     node sdr_boundary_module.mod has no cache_sig!
     node tem_utestenv_module.mod has no cache_sig!
     node sdr_hvs_config_module.mod has no cache_sig!
     node tem_utestenv_module.mod has no cache_sig!
     node tem_utestenv_module.mod has no cache_sig!
     node tem_utestenv_module.mod has no cache_sig!
     node tem_utestenv_module.mod has no cache_sig!
     node sdr_prototree_module.mod has no cache_sig!
     node sdr_config_module.mod has no cache_sig!
     node sdr_boundary_module.mod has no cache_sig!
     node sdr_config_module.mod has no cache_sig!
     node sdr_prototree_module.mod has no cache_sig!
     node sdr_flooding_module.mod has no cache_sig!
     node sdr_proto2treelm_module.mod has no cache_sig!
     node sdr_config_module.mod has no cache_sig!
     Waf: Leaving directory `/Users/klimach/scratch/seeder_test/build/debug'
     Build failed
      -> task in 'sdr_hvs_objs' failed (exit status 1):
        {task 4322363216: fc sdr_hvs_config_module.f90 -> sdr_hvs_config_module.f90.4.o,sdr_hvs_config_module.mod}
     ['mpif90', '-fbacktrace', '-fbounds-check', '-g', '-Wall', '-Wconversion', '-Wimplicit-interface', '-Wunderflow', '-W', '-frange-check', '-Dhas_c_sizeof=1', '-c', '-o', '/Users/klimach/scratch/seeder_test/build/debug/source/sdr_harvesting/sdr_hvs_config_module.f90.4.o', '/Users/klimach/scratch/seeder_test/source/sdr_harvesting/sdr_hvs_config_module.f90']

In the second run all the nodes that are stored have both sigs:

    No missing sig in storing data
    Waf: Leaving directory `/Users/klimach/scratch/seeder_test/build/debug'
    Build failed
    -> task in 'sdr_hvs_objs' failed (exit status 1): 
        	{task 4545577232: fc sdr_hvs_config_module.f90 ->  sdr_hvs_config_module.f90.4.o,sdr_hvs_config_module.mod}
    ['mpif90', '-fbacktrace', '-fbounds-check', '-g', '-Wall', '-Wconversion', '-Wimplicit-interface', '- Wunderflow', '-W', '-frange-check', '-Dhas_c_sizeof=1', '-c', '-o',   '/Users/klimach/scratch/seeder_test/build/debug/source/sdr_harvesting/sdr_hvs_config_module.f90.4.o', '/Users/klimach/scratch/seeder_test/source/sdr_harvesting/sdr_hvs_config_module.f90']

But in the third run there are signatures missing after restoring:

    Haralds-MacBook-Pro:seeder_test klimach$ ./waf debug -j1
    node deps before unpickling:
    node sdr_prototree_module.mod has no sig!
    node sdr_boundary_module.mod has no sig!
    node sdr_hvs_config_module.mod has no sig!
    node sdr_prototree_module.mod has no sig!
    node sdr_boundary_module.mod has no sig!
    node sdr_prototree_module.mod has no sig!
    node sdr_flooding_module.mod has no sig!
    node sdr_proto2treelm_module.mod has no sig!
    node sdr_prototree_module.mod has no sig!
    Waf: Entering directory `/Users/klimach/scratch/seeder_test/build/debug'
    Compiler: GFORTRAN
    Version : 5.1.0
    Flags   : -fbacktrace -fbounds-check -g -Wall -Wconversion -Wimplicit-interface -Wunderflow -W -frange-check
    Using the *dummy* FFTW here!
    Waf: Leaving directory `/Users/klimach/scratch/seeder_test/build/debug'
    Build failed
    Traceback (most recent call last):
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Runner.py", line 150, in task_status
        return tsk.runnable_status()
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Tools/fc.py", line 45, in runnable_status
        ret=tsk.runnable_status()
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Tools/fc.py", line 39, in runnable_status
        return super(fc,self).runnable_status()
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Task.py", line 313, in runnable_status
        new_sig=self.signature()
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Task.py", line 302, in signature
        self.sig_implicit_deps()
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Task.py", line 386, in sig_implicit_deps
        if prev==self.compute_sig_implicit_deps():
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Task.py", line 424, in compute_sig_implicit_deps
        upd(k.get_bld_sig())
      File "/Users/klimach/scratch/seeder_test/.waf-1.8.10-c349aa3c73cab989dcc53b9ba8cc10cf/waflib/Node.py", line 459, in get_bld_sig
        self.cache_sig=ret=self.sig
    AttributeError: sig

**Comment by haraldkl** [comment] 2015-05-29 10:23
I've now put the stuff online. I don't know if it is feasible, but here are the instructions to provoke the problem:

To reproduce you need a Fortran compiler and a MPI library with Fortran compiler wrapper.
Either clone https://bitbucket.org/apesteam/seeder or get the tarball
https://bitbucket.org/apesteam/seeder/downloads/seeder.tgz.
Unpack and change into the seeder directory.
Then run following commands:
$ echo "fail" >> source/sdr_harvesting/sdr_hvs_config_module.f90 
$ export FC=mpif90
$ ./waf distclean
$ ./waf configure
$ ./waf -j1
$ ./waf -j1
$ ./waf -j1

On my Laptop with MacOS it happens after two repititions, on an Archlinux box it happens in the third repitition.

**Comment by ita1024** [comment] 2015-05-29 22:06
I have managed to reproduce the trace. Pleaes replace conf.exec_command by conf.cmd_and_log in the coco compilation. Failure are not detected.

**Comment by haraldkl** [comment] 2015-05-30 01:46
OK, it now reads as reproduced below. This is the place you meant? Or are you referring to something else? I changed the file at https://bitbucket.org/apesteam/seeder/downloads/seeder.tgz now.

    def configure(conf):
        conf.add_os_flags('COCOFLAGS')
        conf.find_program('coco',var='COCO',mandatory=False)
        if not conf.env.COCO:
                mycoco=os.path.abspath(Context.run_dir)+'/coco'
                if not conf.find_program(mycoco,mandatory=False):
                        Logs.warn('Need to compile coco itself...')
                        if not conf.env.FC:
                                conf.fatal('No Fortran Compiler defined yet!')
                        buildcoco=' '.join(conf.env.FC)+' -o '+mycoco+' '+Context.waf_dir+'/waflib/extras/coco.f90'
                        conf.cmd_and_log(buildcoco)

**Comment by haraldkl** [comment] 2015-05-30 02:46
I've now created a version completely without the usage of coco: https://bitbucket.org/apesteam/seeder/downloads/seeder_nococo.tgz
I also removed the utest stuff. This still reproduces the error for me, when following the steps described above.

**Comment by ita1024** [comment] 2015-05-31 13:09
The assumption that node signatures would not disappear was incorrect as you pointed out. Since there are workarounds, I would like to take some time to understand the potential side effects of the changes.

Thanks for researching this and for your patience.

**Comment by haraldkl** [comment] 2015-05-31 13:16
Thank you for listening and your quick responses! Let me know if I could do anything else to shed some light on this.

**Comment by haraldkl** [comment] 2015-05-31 13:46
Would it be an option to put a workaround into the fc.py in the meantime?

Changing

      if not hasattr(node, 'sig'):
          node.sig = Utils.SIG_NIL

to

     if not getattr(node, 'sig', None):
          node.sig = Utils.SIG_NIL

for example?

**Comment by ita1024** [comment] 2015-05-31 14:53
Indeed, this is the best thing for the time being: 92f584fd8f4319d45b9f51e5c76af4197870eda3

**Comment by ita1024** [comment] 2016-03-09 21:16
No more node.sig in waf-1.9 around e6bb4693cb54a3665012dc7742cb80c6c844004e

**Comment by haraldkl** [comment] 2016-03-09 23:10
Seems to work fine, thanks!

**Comment by ita1024** [comment] 2016-06-26 12:17
Waf 1.9.0 was released so we can close this now

**Closed by ita1024** 2016-06-26 12:17 UTC
Labels: waf 1.9
